/*
 * generated by Xtext 2.12.0
 */
package br.org.cursomde.ui;

import br.org.cursomde.exemplo1.ui.internal.Exemplo1Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Exemplo1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Exemplo1Activator.getInstance().getInjector(Exemplo1Activator.BR_ORG_CURSOMDE_MATH);
	}
	
}
