/*
 * generated by Xtext 2.12.0
 */
package br.org.cursomde


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathStandaloneSetup extends MathStandaloneSetupGenerated {

	def static void doSetup() {
		new MathStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
