/**
 * generated by Xtext 2.12.0
 */
package br.org.cursomde.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Armazena</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.org.cursomde.math.MathPackage#getArmazena()
 * @model
 * @generated
 */
public interface Armazena extends Expressao
{
} // Armazena
